### ISSUE TITLE
同学能给我看下你的linux大作业报告吗，不胜感激

### ISSUE THREAD

**Issue by madeirak** [zhanghao731/linux#1]
现在有些无从下手。。。。谢谢
maderiakid@gmail.com

**Comment by zhanghao731** [comment]
> 现在有些无从下手。。。。谢谢
> [maderiakid@gmail.com](mailto:maderiakid@gmail.com)

**Comment by zhanghao731** [comment]
我还没开始写。。要不你看看代码
